version: '3.8'

services:
  kali:
    build: .
    container_name: kali-unit8
    ports:
      - "2229:22"
      - "8087:8080"
    volumes:
      - ./data:/root/data
    environment:
      - TZ=Europe/Madrid
    privileged: true
    restart: unless-stopped
