version: '3.8'

# LABORATORIO 6: EVASIÓN DE DEFENSAS

services:
  kali:
    build: .
    container_name: ethical-hacking-kali
    ports:
      - "2222:22"
      - "6080:8080"
    volumes:
      - ./data:/root/data
    environment:
      - TZ=Europe/Madrid
    networks:
      - lab-network
    privileged: true

  # Windows objetivo con AV
  target-win:
    image: gists/windows-server-core
    container_name: target-windows
    ports:
      - "3389:3389"
    networks:
      - lab-network
    restart: unless-stopped

networks:
  lab-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.61.0/24
